"use client";

import { useEffect, useState } from "react";
import { requestEmailOtp, verifyEmailOtp } from "@/lib/auth/emailOtpClient";
import { isValidBrandEmail, normalizeSafeBrandWebsite } from "@/lib/auth/accountTypes";
import { MintLeafBackButton } from "@/components/ui/MintLeafBackButton";

export function BrandEmailOnboarding({ onBack, onComplete, emailAlreadyVerified = false }: { onBack: () => void; onComplete: () => void; emailAlreadyVerified?: boolean }) {
  const [step, setStep] = useState<"email" | "code" | "profile">(emailAlreadyVerified ? "profile" : "email");
  const [email, setEmail] = useState(""); const [code, setCode] = useState("");
  const [expiresAt, setExpiresAt] = useState<string | null>(null); const [resendAt, setResendAt] = useState<string | null>(null); const [now, setNow] = useState(() => Date.now());
  const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  const [displayName, setDisplayName] = useState(""); const [username, setUsername] = useState("");
  const [bio, setBio] = useState(""); const [website, setWebsite] = useState(""); const [businessCategory, setBusinessCategory] = useState("");
  useEffect(() => { if (!expiresAt) return; const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, [expiresAt]);

  async function sendCode() { if (!isValidBrandEmail(email)) { setError("Enter a valid email address."); return; } setPending(true); setError(null); const result = await requestEmailOtp({ email, accountType: "brand" }); setPending(false); if (!result.ok) { setError(result.message); return; } setEmail(result.challenge.email); setExpiresAt(result.challenge.expiresAt); setResendAt(result.challenge.resendAvailableAt); setNow(Date.now()); setStep("code"); }
  async function requestCode(event: React.FormEvent) { event.preventDefault(); await sendCode(); }
  async function verifyCode(event: React.FormEvent) { event.preventDefault(); setPending(true); setError(null); const result = await verifyEmailOtp({ email, code, accountType: "brand" }); setPending(false); if (!result.ok) { setError(result.message); return; } setStep("profile"); }
  async function completeProfile(event: React.FormEvent) { event.preventDefault(); if (website.trim() && !normalizeSafeBrandWebsite(website)) { setError("Enter a safe http or https website."); return; } setPending(true); setError(null); const response = await fetch("/api/account/complete", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ accountType: "brand", displayName, username, bio, website, businessCategory }) }); const result = await response.json().catch(() => null) as { ok?: boolean; message?: string } | null; setPending(false); if (!response.ok || !result?.ok) { setError(result?.message ?? "We couldn't save your Brand profile."); return; } onComplete(); }

  const inputClass = "w-full rounded-2xl border border-[var(--app-border,#dccdd1)] bg-[var(--app-surface,#fff)] px-4 py-3.5 outline-none focus:ring-2 focus:ring-[var(--app-accent,#6f1d2c)]";
  const resendSeconds = resendAt ? Math.max(0, Math.ceil((Date.parse(resendAt) - now) / 1000)) : 0;
  return <main className="cm-onboarding-scene min-h-dvh bg-[var(--app-background,#f7f1f2)] px-5 py-10 text-[var(--app-text-primary,#2a171b)]"><div className="mx-auto w-full max-w-md py-8">
    <MintLeafBackButton onClick={step === "email" ? onBack : () => { setError(null); setStep(step === "profile" ? "code" : "email"); }} label="Back" className="mb-8" />
    <p className="text-xs font-black uppercase tracking-[.2em] text-[var(--app-accent,#6f1d2c)]">The Campus Mint · Brand</p><h1 className="mt-3 text-4xl font-black tracking-[-.045em]">{step === "email" ? "Brand sign in" : step === "code" ? "Check your email" : "Create your Brand profile"}</h1>
    {step === "email" && <form onSubmit={requestCode} className="mt-8 space-y-4"><input type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@brand.com" className={inputClass}/><button disabled={pending} className="w-full rounded-full bg-[var(--app-accent,#6f1d2c)] px-5 py-3.5 font-black text-white disabled:opacity-50">{pending ? "Sending…" : "Email me a code"}</button></form>}
    {step === "code" && <form onSubmit={verifyCode} className="mt-8 space-y-4"><p className="text-sm text-[var(--app-text-secondary,#725d63)]">Code sent to <strong>{email}</strong> · expires in 10 minutes</p><input type="text" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 6))} aria-label="Verification code" className={`${inputClass} text-center text-2xl font-black tracking-[.24em]`}/><button disabled={pending || code.length !== 6 || Boolean(expiresAt && now >= Date.parse(expiresAt))} className="w-full rounded-full bg-[var(--app-accent,#6f1d2c)] px-5 py-3.5 font-black text-white disabled:opacity-50">{pending ? "Verifying…" : "Verify email"}</button><button type="button" disabled={pending || resendSeconds > 0} onClick={() => { void sendCode(); }} className="w-full rounded-full border border-[var(--app-border,#dccdd1)] px-5 py-3 text-sm font-black disabled:opacity-50">{resendSeconds > 0 ? `Resend in ${resendSeconds}s` : "Resend code"}</button></form>}
    {step === "profile" && <form onSubmit={completeProfile} className="mt-8 space-y-3"><input required value={displayName} onChange={(e) => setDisplayName(e.target.value)} placeholder="Brand name" className={inputClass}/><input required value={username} onChange={(e) => setUsername(e.target.value)} placeholder="Handle" className={inputClass}/><textarea value={bio} onChange={(e) => setBio(e.target.value)} placeholder="Short bio (optional)" className={inputClass}/><input value={website} onChange={(e) => setWebsite(e.target.value)} inputMode="url" placeholder="Website (optional)" className={inputClass}/><input value={businessCategory} onChange={(e) => setBusinessCategory(e.target.value)} placeholder="Business category (optional)" className={inputClass}/><button disabled={pending} className="w-full rounded-full bg-[var(--app-accent,#6f1d2c)] px-5 py-3.5 font-black text-white disabled:opacity-50">{pending ? "Saving…" : "Create Brand profile"}</button></form>}
    {error && <p role="alert" className="mt-4 text-sm font-semibold text-red-700">{error}</p>}<p className="mt-6 text-xs leading-5 text-[var(--app-text-secondary,#725d63)]">Brand approval required</p>
  </div></main>;
}
