/* eslint-disable @next/next/no-img-element */
'use client';
import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { createPortal } from 'react-dom';
import { useModalLayer } from '@/hooks/useModalLayer';
import { useCampusPreview } from '@/components/developer/CampusPreviewContext';
import { canManageClub, canRemoveClubMember, type ClubView, type ClubPerson } from '@/lib/clubs/contracts';

const control='rounded-full px-3 py-2 text-sm font-semibold text-[var(--app-accent)] disabled:opacity-40';
const field='w-full rounded-2xl border-0 bg-[var(--app-surface-elevated)] px-3 py-3 text-[var(--app-text-primary)]';
async function getClubs(url:string) { const response=await fetch(url,{cache:'no-store'}); const result=await response.json(); if(!response.ok)throw new Error(result.message??'Clubs unavailable.'); return result as {clubs:ClubView[];people?:ClubPerson[]}; }

function ClubEditor({club,onClose,onSave,busy}:{club?:ClubView;onClose:()=>void;onSave:(data:Record<string,unknown>)=>Promise<void>;busy:boolean}) {
  const ref=useRef<HTMLDivElement>(null); useModalLayer(ref,()=>{if(!busy)onClose();});
  const [error,setError]=useState('');
  async function submit(event:FormEvent<HTMLFormElement>) { event.preventDefault(); const data=Object.fromEntries(new FormData(event.currentTarget)); try {await onSave({...data,tags:String(data.tags??'').split(',').map(s=>s.trim()).filter(Boolean)});}catch(error){setError(error instanceof Error?error.message:'Save failed.');} }
  return createPortal(<div className="fixed inset-0 z-[160] flex items-center justify-center bg-black/40 p-4" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onClose();}}><div ref={ref} role="dialog" aria-modal="true" aria-labelledby="club-editor-title" tabIndex={-1} className="cm-create-composer max-h-[85dvh] w-full max-w-lg overflow-y-auto rounded-3xl bg-[var(--app-surface)] p-6 text-[var(--app-text-primary)]"><div className="flex justify-between"><h2 id="club-editor-title" className="text-xl font-bold">{club?'Edit club':'Create club'}</h2><button type="button" aria-label="Close" disabled={busy} onClick={onClose}>×</button></div><form onSubmit={event=>void submit(event)} className="mt-5 space-y-3"><label className="block text-sm">Name<input data-initial-focus name="name" defaultValue={club?.name} required minLength={2} maxLength={160} className={field}/></label>{!club&&<label className="block text-sm">Handle<input name="handle" required pattern="[a-z0-9][a-z0-9-]{2,63}" minLength={3} maxLength={64} className={field}/></label>}<label className="block text-sm">Description<textarea name="description" defaultValue={club?.description} required minLength={2} maxLength={5000} rows={4} className={field}/></label>{club&&<><label className="block text-sm">Visibility<select name="visibility" defaultValue={club.visibility} disabled={club.role!=='leader'} className={field}><option value="private">Private</option><option value="public">Public</option></select>{club.role!=='leader'&&<input type="hidden" name="visibility" value={club.visibility}/>}</label><label className="block text-sm">Meetup location<input name="location" defaultValue={club.location} maxLength={200} className={field}/></label><label className="block text-sm">Meeting times<input name="schedule" defaultValue={club.schedule} maxLength={200} className={field}/></label><label className="block text-sm">Website<input name="website" type="url" defaultValue={club.website??''} className={field}/></label><label className="block text-sm">Cover image link<input name="photo" type="url" defaultValue={club.photo??''} className={field}/></label><label className="block text-sm">Interests<input name="tags" defaultValue={club.tags?.join(', ')} placeholder="Hiking, photography" maxLength={320} className={field}/></label></>}{!club&&<p className="text-sm">Private · Approval required</p>}{error&&<p role="alert" className="text-[var(--app-danger)]">{error}</p>}<div className="text-right"><button disabled={busy} className={control}>{busy?'Saving…':club?'Save':'Create'}</button></div></form></div></div>,document.body);
}

export function LiveClubs({universityId,currentUserId}:{universityId:string|null;currentUserId:string}) {
  const readOnly=useCampusPreview(); const [clubs,setClubs]=useState<ClubView[]>([]); const [selected,setSelected]=useState<ClubView|null>(null);
  const [tab,setTab]=useState<'discover'|'mine'>('discover'); const [query,setQuery]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [editor,setEditor]=useState<'create'|'edit'|null>(null);
  const [peopleQuery,setPeopleQuery]=useState(''); const [people,setPeople]=useState<ClubPerson[]|null>(null); const [inviteOpen,setInviteOpen]=useState(false); const [sent,setSent]=useState<string[]>([]);
  const generation=useRef(0);
  const base='/api/clubs?'+new URLSearchParams(universityId?{universityId}:{});
  const refresh=useCallback(async()=>{const result=await getClubs(base);setClubs(result.clubs);},[base]);
  useEffect(()=>{let active=true;getClubs(base).then(result=>{if(active){setClubs(result.clubs);setError('');}}).catch(error=>{if(active)setError(error.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[base]);
  async function open(id:string) { const current=++generation.current;setError('');setPeople(null);setInviteOpen(false); try {const result=await getClubs(`${base}&id=${id}`);if(current===generation.current)setSelected(result.clubs[0]??null);}catch(error){if(current===generation.current)setError(error instanceof Error?error.message:'Club unavailable.');} }
  async function act(action:string,clubId?:string,targetId?:string,data:Record<string,unknown>={}) {
    if(readOnly)throw new Error('Campus preview is read-only.');setBusy(true);setError('');
    try {const response=await fetch('/api/clubs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,action,clubId,targetId})});const result=await response.json();if(!response.ok)throw new Error(result.message??'Club update failed.');await refresh();if(action==='create'){setEditor(null);await open(result.id);}else if(selected&&action!=='invite'){const detail=await getClubs(`${base}&id=${selected.id}`);setSelected(detail.clubs[0]??null);}if(action==='update')setEditor(null);if(action==='invite'&&targetId)setSent(current=>[...current,targetId]);}
    catch(error){setError(error instanceof Error?error.message:'Club update failed.');throw error;}finally{setBusy(false);}
  }
  const run=(action:string,id?:string,target?:string)=>void act(action,id,target).catch(()=>{});
  async function searchPeople(event?:FormEvent) {event?.preventDefault();if(!selected)return;const current=++generation.current;setError('');try{const result=await getClubs(`${base}&id=${selected.id}&people=${encodeURIComponent(peopleQuery)}`);if(current===generation.current){setPeople(result.people??[]);setInviteOpen(true);}}catch(error){if(current===generation.current)setError(error instanceof Error?error.message:'Search unavailable.');}}
  const visible=clubs.filter(club=>(tab==='discover'||['leader','officer','member'].includes(club.role??'')||club.invited)&&`${club.name} ${club.summary}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="space-y-5 text-[var(--app-text-primary)]" data-live-clubs><header className="flex items-center justify-between"><h1 className="text-2xl font-bold">Clubs</h1><button className={control} disabled={busy||readOnly} onClick={()=>setEditor('create')}>+ Create Club</button></header>{error&&<p role="alert" className="text-sm text-[var(--app-danger)]">{error}<button className={control} onClick={()=>void refresh().then(()=>setError('')).catch(()=>{})}>Retry</button></p>}
    {selected?<><div className="flex items-center justify-between"><button className={control} onClick={()=>{generation.current++;setSelected(null);setInviteOpen(false);}}>All clubs</button>{selected.editable&&canManageClub(selected.role)&&<button className={control} disabled={readOnly||busy} onClick={()=>setEditor('edit')}>Edit</button>}</div>{selected.photo&&<img src={selected.photo} alt="" referrerPolicy="no-referrer" className="max-h-64 w-full rounded-3xl object-cover"/>}<h2 className="text-3xl font-bold">{selected.name}</h2><p className="text-sm">{selected.visibility==='private'?'Private':'Public'} · {selected.memberCount} members</p><p className="whitespace-pre-wrap">{selected.description??selected.summary}</p>{selected.location&&<p>{selected.location}</p>}{selected.schedule&&<p>{selected.schedule}</p>}{selected.website&&<a className={control} href={selected.website} target="_blank" rel="noreferrer">Website ↗</a>}
      {selected.editable&&<div className="flex gap-2">{selected.invited&&!['leader','officer','member'].includes(selected.role??'')?<><button className={control} disabled={busy||readOnly} onClick={()=>run('accept_invite',selected.id)}>Accept invitation</button><button className={control} disabled={busy||readOnly} onClick={()=>run('decline_invite',selected.id)}>Decline</button></>:selected.role==='leader'?null:selected.role==='requested'?<button className={control} disabled={busy||readOnly} onClick={()=>run('cancel',selected.id)}>Cancel request</button>:selected.role?<button className={control} disabled={busy||readOnly} onClick={()=>run('leave',selected.id)}>Leave club</button>:<button className={control} disabled={busy||readOnly} onClick={()=>run('request',selected.id)}>Request to join</button>}</div>}
      {canManageClub(selected.role)&&selected.editable&&<><button className={control} disabled={busy||readOnly} onClick={()=>void searchPeople()}>+ Invite people</button>{inviteOpen&&<section className="space-y-3 rounded-3xl bg-[var(--app-surface)] p-4"><form onSubmit={event=>void searchPeople(event)} className="flex gap-2"><input aria-label="Find people" placeholder="Name or username" value={peopleQuery} maxLength={60} onChange={event=>{generation.current++;setPeopleQuery(event.target.value);setPeople(null);}} className={field}/><button className={control}>Search</button></form>{people?.map(person=><div key={person.id} className="flex items-center justify-between gap-3"><span>{person.name} <span className="text-sm">@{person.username}</span></span><button className={control} disabled={busy||sent.includes(person.id)||readOnly} onClick={()=>run('invite',selected.id,person.id)}>{sent.includes(person.id)?'Invited':'Invite'}</button></div>)}{people?.length===0&&<p className="py-4 text-center">No matches</p>}</section>}
        <h3 className="font-semibold">Members & requests</h3>{selected.members?.map(person=><div key={person.id} className="flex flex-wrap items-center justify-between gap-2 py-2"><div>{person.name}<span className="ml-2 text-xs">{person.role==='leader'?'Owner':person.role==='officer'?'Admin':person.role==='requested'?'Requested':'Member'}</span></div><div className="flex gap-1">{person.role==='requested'?<><button disabled={busy||readOnly} className={control} onClick={()=>run('approve',selected.id,person.id)}>Accept</button><button disabled={busy||readOnly} className={control} onClick={()=>run('reject',selected.id,person.id)}>Decline</button></>:<>{selected.role==='leader'&&person.role!=='leader'&&<button disabled={busy||readOnly} className={control} onClick={()=>run(person.role==='officer'?'demote':'promote',selected.id,person.id)}>{person.role==='officer'?'Remove admin':'Make admin'}</button>}{person.id!==currentUserId&&canRemoveClubMember(selected.role,person.role)&&<button disabled={busy||readOnly} className={control} onClick={()=>run('remove',selected.id,person.id)}>Remove</button>}</>}</div></div>)}</>}
    </>:<><nav className="flex gap-3" aria-label="Club views">{(['discover','mine'] as const).map(value=><button key={value} type="button" aria-pressed={tab===value} onClick={()=>setTab(value)} className={control} style={{background:tab===value?'var(--app-accent-soft)':'transparent'}}>{value==='discover'?'Discover':'My clubs'}</button>)}</nav><input aria-label="Search clubs" placeholder="Search clubs" value={query} onChange={event=>setQuery(event.target.value)} className={field}/>{loading?<p role="status" className="py-10 text-center">Loading…</p>:visible.length?<div className="grid gap-4 sm:grid-cols-2">{visible.map(club=><button key={club.id} type="button" onClick={()=>void open(club.id)} className="rounded-3xl bg-[var(--app-surface)] p-5 text-left"><h2 className="text-lg font-bold">{club.name}</h2><p className="mt-2 line-clamp-2 text-sm">{club.summary}</p><p className="mt-3 text-xs text-[var(--app-accent)]">{!club.editable?'View club':club.invited?'Invitation':club.role==='requested'?'Request pending':club.role?'Your club':club.visibility==='private'?'Private · Request to join':'Request to join'}</p></button>)}</div>:<p className="py-12 text-center">No clubs yet</p>}</>}
    {editor&&<ClubEditor key={editor==='edit'?selected?.id:'new'} club={editor==='edit'?selected??undefined:undefined} busy={busy} onClose={()=>setEditor(null)} onSave={data=>act(editor==='create'?'create':'update',editor==='edit'?selected?.id:undefined,undefined,data)}/>}
  </section>;
}
