-- Intentionally empty.
-- Organization source rows are created only after a reviewed official API or
-- feed has a real URL and adapter. Local organization fixtures live outside
-- the production migration history.
